services:
  - type: web
    name: bussola-bolso-backend
    runtime: node
    buildCommand: npm install --prefix backend && npm run build --prefix backend
    startCommand: npx prisma migrate deploy --schema backend/prisma/schema.prisma && npm start --prefix backend
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromConfig: true
      - key: JWT_SECRET
        generateValue: true
